#!/usr/bin/env python3
"""Stamp the service catalogue into the two hand-maintained places that list it.

    python3 scripts/apply-capability-index.py            # rewrite
    python3 scripts/apply-capability-index.py --check    # CI: fail if stale

The capabilities live in content/capabilities/*.md and are rendered to pages
by build-content.py. Two hand-maintained files also list them, and both used
to be typed by hand:

  services.html   the "Every capability, mapped." explorer — 59 chips that
                  were <span>s, so nothing a visitor clicked went anywhere
  site.js         the Services mega-menu — 39 names, 3 with a real link, the
                  rest falling through to the top of services.html

Hand-typed lists drift (the two already disagreed on names and counts). This
script regenerates both from the Markdown between delimited markers, the same
way apply-page-seo.py owns the SEO block, and --check makes CI refuse a commit
where the chips and the pages no longer match.
"""
from __future__ import print_function

import glob
import io
import json
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from lib.catalogue import load_catalogue  # noqa: E402
from lib.html import esc  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CONTENT = os.path.join(ROOT, "content")
SERVICES_HTML = os.path.join(ROOT, "services.html")
SITE_JS = os.path.join(ROOT, "assets", "js", "site.js")

COUNT_BEGIN = "<!-- gispl:capability-count:begin — generated by scripts/apply-capability-index.py, do not hand-edit -->"
COUNT_END = "<!-- gispl:capability-count:end -->"
EXPLORER_BEGIN = "<!-- gispl:capability-explorer:begin — generated by scripts/apply-capability-index.py, do not hand-edit -->"
EXPLORER_END = "<!-- gispl:capability-explorer:end -->"
JS_BEGIN = "/* gispl:svc:begin — generated by scripts/apply-capability-index.py, do not hand-edit */"
JS_END = "/* gispl:svc:end */"

CHECK = ('<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.4" '
         'stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">'
         '<path d="M4.5 12.5l5 5L19.5 7"/></svg>')


def block(text, begin, end, body, where):
    pattern = re.compile(re.escape(begin) + r".*?" + re.escape(end), re.S)
    if not pattern.search(text):
        raise SystemExit("ERROR: %s has no %s … %s markers" % (where, begin[:32], end))
    return pattern.sub(lambda m: begin + body + end, text, count=1)


def site_href(url):
    """Root-relative catalogue URL -> the relative form the hand pages use."""
    return url.lstrip("/")


def explorer_html(practices):
    rail = []
    panels = []
    for i, p in enumerate(practices):
        caps = p["capabilities"]
        on = i == 0
        rail.append(
            '<button class="sv-x-tab" role="tab" id="svTab%d" aria-selected="%s" '
            'aria-controls="svPanel%d" data-x="%d" tabindex="%s" type="button">'
            '<span>%s</span><span class="sv-x-count">%02d</span></button>'
            % (i, "true" if on else "false", i, i, "0" if on else "-1", esc(p["title"]), len(caps)))
        chips = "".join(
            '<a class="sv-x-item" href="%s">%s%s</a>' % (esc(site_href(c["url"])), CHECK, esc(c["label"]))
            for c in caps)
        panels.append(
            '<div class="sv-x-panel%s" role="tabpanel" id="svPanel%d" aria-labelledby="svTab%d" '
            'data-xp="%d" tabindex="0">'
            '<p style="font:400 15px/1.6 \'IBM Plex Sans\';color:#5B647C;margin:0 0 22px;max-width:56ch">'
            '%s <a href="%s" style="color:#C4632A;font-weight:600;text-decoration:none;white-space:nowrap">'
            'About this practice &rarr;</a></p>'
            '<div style="display:flex;gap:10px;flex-wrap:wrap">%s</div></div>'
            % (" sv-x-live" if on else "", i, i, i, esc(p["lead"]), esc(site_href(p["url"])), chips))
    return ('<div class="sv-x sv-rv" style="--d:.12s"><div class="sv-x-rail" role="tablist" '
            'aria-label="Capability areas">%s</div>%s</div>' % ("".join(rail), "".join(panels)))


def count_html(practices, total):
    return ('<span class="sv-rv" style="--d:.1s;font:500 12px \'IBM Plex Mono\';letter-spacing:.1em;'
            'color:#5B647C">%d CAPABILITIES · %d PRACTICE AREAS · '
            '<a href="services/" style="color:#C4632A;text-decoration:none">FULL CATALOGUE &rarr;</a></span>'
            % (total, len(practices)))


def js_block(practices):
    """The mega-menu data. Hrefs are root-relative without the leading slash;
    site.js prefixes GX_ROOT so they resolve from any page depth or sub-path."""
    data = []
    for p in practices:
        data.append({
            "name": p["title"],
            "blurb": p["lead"],
            "href": site_href(p["url"]),
            "items": [{"n": c["label"], "h": site_href(c["url"])} for c in p["capabilities"]],
        })
    lines = ["\n  var SVC = ["]
    for d in data:
        lines.append("    " + json.dumps(d, ensure_ascii=False, separators=(", ", ": ")) + ",")
    lines.append("  ];\n  ")
    return "\n".join(lines)


# The header's server-rendered mega-menu list. site.js repaints it from SVC on
# load, but the static copy is what a crawler, a no-JS visitor and the
# header-sync guard see — so it is stamped from the same data.
_SVC_ITEMS = re.compile(r'(<div id="svcItems"[^>]*>).*?(</div>)', re.S)
_SEE_ALL = re.compile(r'(<a href=")[^"]*(" class="gx-explore-link"[^>]*>See all &rarr;</a>)')
_EXPLORE_ALL = re.compile(r'(<a href=")[^"]*(" class="gx-explore-link"[^>]*>Explore all services <span[^>]*>&rarr;</span></a>)')


def header_items_html(practice):
    return "".join(
        '<a class="gx-svc-item" href="%s" style="text-decoration:none;display:flex;align-items:center;'
        'gap:9px;padding:9px 0;font:500 14px \'IBM Plex Sans\';line-height:1.3">%s</a>'
        % (esc(site_href(c["url"])), esc(c["label"])) for c in practice["capabilities"])


def stamp_header(html, practices):
    """Rewrite the static mega-menu on one hand-maintained page."""
    first = practices[0]
    html = _SVC_ITEMS.sub(lambda m: m.group(1) + header_items_html(first) + m.group(2), html, count=1)
    html = _SEE_ALL.sub(lambda m: m.group(1) + site_href(first["url"]) + m.group(2), html, count=1)
    html = _EXPLORE_ALL.sub(lambda m: m.group(1) + "services/" + m.group(2), html, count=1)
    return html


def main():
    check = "--check" in sys.argv
    practices, capabilities, _ = load_catalogue(CONTENT)
    total = len(capabilities)

    orphans = [c["slug"] for c in capabilities if not c["practice"] or
               c["practice"] not in {p["slug"] for p in practices}]
    if orphans:
        print("ERROR: capabilities with no practice: %s" % ", ".join(orphans), file=sys.stderr)
        return 1

    changed = []
    for path, edits in (
        (SERVICES_HTML, [(COUNT_BEGIN, COUNT_END, count_html(practices, total)),
                         (EXPLORER_BEGIN, EXPLORER_END, explorer_html(practices))]),
        (SITE_JS, [(JS_BEGIN, JS_END, js_block(practices))]),
    ):
        with io.open(path, encoding="utf-8") as fh:
            before = fh.read()
        after = before
        for begin, end, body in edits:
            after = block(after, begin, end, body, os.path.relpath(path, ROOT))
        if after != before:
            changed.append(os.path.relpath(path, ROOT))
            if not check:
                with io.open(path, "w", encoding="utf-8") as fh:
                    fh.write(after)

    # Every page that carries the shared header gets the same static list.
    for path in sorted(glob.glob(os.path.join(ROOT, "*.html"))):
        with io.open(path, encoding="utf-8") as fh:
            before = fh.read()
        if 'id="svcItems"' not in before:
            continue
        after = stamp_header(before, practices)
        if after != before:
            changed.append(os.path.relpath(path, ROOT))
            if not check:
                with io.open(path, "w", encoding="utf-8") as fh:
                    fh.write(after)

    if check:
        if changed:
            print("STALE: %s — run scripts/apply-capability-index.py" % ", ".join(changed),
                  file=sys.stderr)
            return 1
        print("capability index current: %d capabilities in %d practices"
              % (total, len(practices)))
        return 0
    if changed:
        print("updated %s (%d capabilities, %d practices)"
              % (", ".join(changed), total, len(practices)))
    else:
        print("already current (%d capabilities, %d practices)" % (total, len(practices)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
