#!/usr/bin/env python3
"""Stamp canonical / og:url / og:image / JSON-LD into the hand-maintained pages.

    .venv/bin/python scripts/apply-page-seo.py          # write
    .venv/bin/python scripts/apply-page-seo.py --check   # verify, exit 1 on drift

Generated pages already carry all of this (scripts/build-content.py emits it).
The 11 hand-written pages did not: verified across the repo, there were 0
canonicals, 0 og:url, 0 og:image and 0 JSON-LD blocks anywhere.

This edits ONLY the <head>, between two marker comments, so it is idempotent
and cannot touch the header/footer that check-header-sync.py guards. Re-running
it replaces the block rather than appending a second one.

Absolute production URLs are used throughout, so a preview host never
advertises itself as canonical.
"""
from __future__ import print_function

import io
import json
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import yaml  # noqa: E402

from lib import seo  # noqa: E402
from lib.html import esc  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CONTENT = os.path.join(ROOT, "content")

BEGIN = "<!-- gispl:seo:begin — generated by scripts/apply-page-seo.py, do not hand-edit -->"
END = "<!-- gispl:seo:end -->"

BLOCK = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.S)
# Tags this block owns. Any pre-existing copy outside the block is removed so
# a page can never carry two conflicting og:title values.
OWNED = re.compile(
    r'\s*<link[^>]+rel="canonical"[^>]*>'
    r'|\s*<meta[^>]+property="og:(?:url|image|title|description|type|site_name)"[^>]*>'
    r'|\s*<meta[^>]+name="twitter:card"[^>]*>',
    re.I,
)

TITLE = re.compile(r"<title>(.*?)</title>", re.S | re.I)
DESC = re.compile(r'<meta\s+name="description"\s+content="(.*?)"\s*/?>', re.S | re.I)
HEAD_CLOSE = re.compile(r"</head>", re.I)

# contact.html's FAQ is a <details> accordion; the schema is built from the
# rendered text so the markup can never claim an answer the page doesn't show.
DETAILS = re.compile(r"<details[^>]*>(.*?)</details>", re.S | re.I)
SUMMARY = re.compile(r"<summary[^>]*>(.*?)</summary>", re.S | re.I)
TAGS = re.compile(r"<[^>]+>")


def text_of(html):
    t = TAGS.sub(" ", html)
    t = (t.replace("&amp;", "&").replace("&lt;", "<").replace("&gt;", ">")
          .replace("&quot;", '"').replace("&#39;", "'").replace("&nbsp;", " ")
          .replace("&rarr;", "").replace("&larr;", "").replace("&times;", "x")
          .replace("&hellip;", "..."))
    return " ".join(t.split())


# The accordion's open/close indicator is a sibling <span class="gx-faq-x">+</span>
# inside <summary>. Left in, every schema question ends in " +", which is what
# would show in a rich result.
FAQ_INDICATOR = re.compile(r'<span[^>]*class="gx-faq-x"[^>]*>.*?</span>', re.S | re.I)


def faq_pairs(html):
    pairs = []
    for block in DETAILS.findall(html):
        m = SUMMARY.search(block)
        if not m:
            continue
        question = text_of(FAQ_INDICATOR.sub("", m.group(1)))
        question = question.rstrip(" +-−×").strip()
        answer = text_of(SUMMARY.sub("", block, count=1))
        if question and answer:
            pairs.append((question, answer))
    return pairs


def build_block(site, page, html):
    path = page["path"]
    url = seo.absolute(site["baseUrl"], path)
    title_m = TITLE.search(html)
    desc_m = DESC.search(html)
    title = text_of(title_m.group(1)) if title_m else page["title"]
    description = text_of(desc_m.group(1)) if desc_m else site.get("description", "")
    # <title> is an SEO field and carries keywords; the social card is a brand
    # surface and carries positioning. Pages that want them to differ set
    # `ogTitle` in pages.yml — otherwise og:title still mirrors <title>, so the
    # two can never silently drift.
    title = page.get("ogTitle") or title
    image = seo.absolute(site["baseUrl"], site.get("defaultOgImage"))

    lines = [
        BEGIN,
        '<link rel="canonical" href="%s">' % esc(url),
        '<meta property="og:type" content="website">',
        '<meta property="og:site_name" content="%s">' % esc(site.get("siteName")),
        '<meta property="og:title" content="%s">' % esc(title),
        '<meta property="og:description" content="%s">' % esc(description),
        '<meta property="og:url" content="%s">' % esc(url),
        '<meta property="og:image" content="%s">' % esc(image),
        '<meta name="twitter:card" content="summary_large_image">',
    ]

    blocks = [seo.organization(site)]

    trail = [("Home", "/")]
    parent = page.get("parent")
    if parent:
        for other in PAGES:
            if other["path"] == parent:
                trail.append((other.get("breadcrumb", other["title"]), parent))
                break
    if path != "/":
        trail.append((page.get("breadcrumb", page["title"]), path))
    if len(trail) > 1:
        blocks.append(seo.breadcrumbs(site, trail))

    kind = page.get("schema")
    if kind == "website":
        blocks.append(seo.website(site))
        blocks.extend(seo.local_businesses(site))
    elif kind == "service":
        blocks.append(seo.service(site, page["title"], description, url,
                                  page.get("serviceType")))
    elif kind == "contact":
        blocks.extend(seo.local_businesses(site))
        faq = seo.faq_page(faq_pairs(html))
        if faq:
            blocks.append(faq)

    for b in blocks:
        lines.append('<script type="application/ld+json">%s</script>'
                     % json.dumps(b, ensure_ascii=False, separators=(",", ":")))
    lines.append(END)
    return "\n".join(lines)


def apply_to(path_on_disk, site, page, check):
    with io.open(path_on_disk, encoding="utf-8") as fh:
        html = fh.read()

    stripped = BLOCK.sub("", html)
    stripped = OWNED.sub("", stripped)
    if not HEAD_CLOSE.search(stripped):
        return None, "no </head>"

    # Removing the block leaves the whitespace that preceded it, so without
    # normalising here every run would differ from the last by one newline and
    # --check would never go green.
    stripped = re.sub(r"\s*</head>", "\n</head>", stripped, count=1)

    block = build_block(site, page, stripped)
    out = stripped.replace("</head>", block + "\n</head>", 1)
    if out == html:
        return False, None
    if not check:
        with io.open(path_on_disk, "w", encoding="utf-8") as fh:
            fh.write(out)
    return True, None


def main():
    check = "--check" in sys.argv
    with io.open(os.path.join(CONTENT, "site.yml"), encoding="utf-8") as fh:
        site = yaml.safe_load(fh)
    with io.open(os.path.join(CONTENT, "pages.yml"), encoding="utf-8") as fh:
        global PAGES
        PAGES = yaml.safe_load(fh)

    changed, errors = [], []
    for page in PAGES:
        if page.get("generated"):
            continue  # emitted by build-content.py, which stamps its own head
        target = os.path.join(ROOT, page["file"])
        if not os.path.exists(target):
            errors.append("%s: listed in pages.yml but missing on disk" % page["file"])
            continue
        did, err = apply_to(target, site, page, check)
        if err:
            errors.append("%s: %s" % (page["file"], err))
        elif did:
            changed.append(page["file"])

    for e in errors:
        print("ERROR: " + e, file=sys.stderr)
    if check:
        if changed:
            print("SEO block out of date in %d page(s): %s"
                  % (len(changed), ", ".join(changed)), file=sys.stderr)
            print("  run: .venv/bin/python scripts/apply-page-seo.py", file=sys.stderr)
        else:
            print("SEO blocks up to date")
        return 1 if (changed or errors) else 0

    print("stamped SEO into %d page(s)%s"
          % (len(changed), (": " + ", ".join(changed)) if changed else " (all current)"))
    return 1 if errors else 0


if __name__ == "__main__":
    sys.exit(main())
